### ISSUE TITLE
Quickstarts tests broken due to wrong version in pom

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak-quickstarts#320] opened 2022-05-19 06:02 UTC
### Describe the bug

the module `user-storage-jpa-legacy` still declares `18.0.0-SNAPSHOT` as development version. lately this was changed to use `999-SNAPSHOT` instead. This causes the main repo CI step `Quickstarts Tests` to break, see e.g. https://github.com/keycloak/keycloak/runs/6493560232?check_suite_focus=true#step:8:4617

### Version

current

### Expected behavior

the error does not show up anymore.

### Actual behavior

error shows up.

### Anything else?

will provide a pr

**Comment by ahus1** [comment] 2022-06-09 16:48
has been implemented, unclear why the issue is still open. Closing it.

**Closed by ahus1** 2022-06-09 16:48 UTC
Labels: kind/bug
